export {Aside} from './Aside/Aside';
export {AsideTabs} from './AsideTabs/AsideTabs';
export {MoviesSection} from './MoviesSection/MoviesSection';
export {SearchInput} from './SearchInput/SearchInput';
export {Dropdown} from './Dropdown/Dropdown';
export {NumInput} from './NumInput/NumInput';
export {RatingInputs} from './RatingInputs/RatingInputs';
export {MovieCard} from './MovieCard/MovieCard';
export {GenresDropdown} from './GenresDropdown/GenresDropdown';
