export const mockGenres = {
  genres: [
    {
      id: 28,
      name: 'Action',
    },
    {
      id: 12,
      name: 'Adventure',
    },
    {
      id: 16,
      name: 'Animation',
    },
    {
      id: 35,
      name: 'Comedy',
    },
    {
      id: 80,
      name: 'Crime',
    },
    {
      id: 99,
      name: 'Documentary',
    },
    {
      id: 18,
      name: 'Drama',
    },
    {
      id: 10751,
      name: 'Family',
    },
    {
      id: 14,
      name: 'Fantasy',
    },
    {
      id: 36,
      name: 'History',
    },
    {
      id: 27,
      name: 'Horror',
    },
    {
      id: 10402,
      name: 'Music',
    },
    {
      id: 9648,
      name: 'Mystery',
    },
    {
      id: 10749,
      name: 'Romance',
    },
    {
      id: 878,
      name: 'Science Fiction',
    },
    {
      id: 10770,
      name: 'TV Movie',
    },
    {
      id: 53,
      name: 'Thriller',
    },
    {
      id: 10752,
      name: 'War',
    },
    {
      id: 37,
      name: 'Western',
    },
  ],
};

export const mockMovies = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/7iwUUcKURMT7aKfCwMy6YnGtchD.jpg',
      genre_ids: [878, 28, 12],
      id: 969681,
      title: 'Spider-Man: Brand New Day',
      original_language: 'en',
      original_title: 'Spider-Man: Brand New Day',
      overview:
        "Fighting crime full-time as Spider-Man in a world that doesn't remember him—and the pressure of seeing his old friends move on without him—sparks a change in Peter Parker he may not have the power to control. But that transformation might also be the only thing that can stop a shocking new threat to the city and those he loves - a powerful villain no one can even see.",
      popularity: 1875.3748,
      poster_path: '/iPOn6DinuVyLY17YM9mKuPofV08.jpg',
      release_date: '2026-07-29',
      softcore: false,
      video: false,
      vote_average: 7.885,
      vote_count: 1953,
    },
    {
      adult: false,
      backdrop_path: '/r57L2UBLPKcHdZQYg8tagv9XqK2.jpg',
      genre_ids: [12, 28, 14],
      id: 1368337,
      title: 'The Odyssey',
      original_language: 'en',
      original_title: 'The Odyssey',
      overview:
        'Odysseus, the legendary King of Ithaca, embarks on a long and perilous journey home following the Trojan War. Throughout his voyage, he is forced to confront the whims of gods, mythological monsters, and trials that stretch both his cunning and his humanity to the breaking point.',
      popularity: 728.3957,
      poster_path: '/5rhTDKUhPYvpdQIijFIs5VoWsON.jpg',
      release_date: '2026-07-15',
      softcore: false,
      video: false,
      vote_average: 7.982,
      vote_count: 2975,
    },
    {
      adult: false,
      backdrop_path: '/uyrOU4BDm2kbVxFsMiDFIHDhc4d.jpg',
      genre_ids: [28, 12, 878],
      id: 634649,
      title: 'Spider-Man: No Way Home',
      original_language: 'en',
      original_title: 'Spider-Man: No Way Home',
      overview:
        'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.',
      popularity: 386.8832,
      poster_path: '/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg',
      release_date: '2021-12-15',
      softcore: false,
      video: false,
      vote_average: 7.94,
      vote_count: 22756,
    },
    {
      adult: false,
      backdrop_path: '/8sSKdEmlmqF4kJUd28SqthXC4yZ.jpg',
      genre_ids: [16, 10751, 35, 12],
      id: 1084244,
      title: 'Toy Story 5',
      original_language: 'en',
      original_title: 'Toy Story 5',
      overview:
        "When Bonnie receives a Lilypad tablet as a gift and becomes obsessed, Buzz, Woody, Jessie and the rest of the gang's jobs become exponentially harder when they have to go head to head with the all-new threat to playtime.",
      popularity: 404.7642,
      poster_path: '/sfQtVlIHljToOwYjhe21KPGzZWK.jpg',
      release_date: '2026-06-17',
      softcore: false,
      video: false,
      vote_average: 7.9,
      vote_count: 1177,
    },
    {
      adult: false,
      backdrop_path: '/z7lZgL5tzefTfhyRtouThFhsuUS.jpg',
      genre_ids: [28, 878, 53],
      id: 1323244,
      title: 'Rage of Stars',
      original_language: 'en',
      original_title: 'Rage of Stars',
      overview:
        'A story about a woman from the International Special Forces Unit, who has a premonition about the impending end of humanity.',
      popularity: 370.7603,
      poster_path: '/oLld47ZT1I3iecM3OWhIphohQUJ.jpg',
      release_date: '2026-08-06',
      softcore: false,
      video: false,
      vote_average: 4.833,
      vote_count: 6,
    },
    {
      adult: false,
      backdrop_path: '/84FEpVVbSKYvKXDZJDZXOKBxCEm.jpg',
      genre_ids: [28, 27, 878],
      id: 1375646,
      title: 'Colony',
      original_language: 'ko',
      original_title: '군체',
      overview:
        'Professor Se-jeong is thrust into a bloody nightmare when a rapidly mutating virus is released during a biotech conference causing authorities to seal the facility. Trapped inside with no escape, Se-jeong along with a small group of survivors must fight to stay alive while the infected undergo horrific transformations.',
      popularity: 292.2132,
      poster_path: '/tN799oUR0f1gUKDYdMNrDaY7I51.jpg',
      release_date: '2026-05-21',
      softcore: false,
      video: false,
      vote_average: 8.104,
      vote_count: 550,
    },
    {
      adult: false,
      backdrop_path: '/kkcwhgSFd81QDlXo8ytrpHPQjhy.jpg',
      genre_ids: [12, 16, 35, 10751, 14],
      id: 1315772,
      title: 'Minions & Monsters',
      original_language: 'en',
      original_title: 'Minions & Monsters',
      overview:
        'This is the rambunctious, ridiculous and totally true story of how the Minions conquered Hollywood, became movie stars, lost everything, unleashed monsters onto the world and then banded together to try and save the planet from the mayhem they had just created.',
      popularity: 264.2694,
      poster_path: '/4LwvU9SZc8QQzW1X1FAPhNbXnEU.jpg',
      release_date: '2026-06-24',
      softcore: false,
      video: false,
      vote_average: 7.5,
      vote_count: 757,
    },
    {
      adult: false,
      backdrop_path: '/1RhfevWmWCVHtEqxWBEjPOC5KG1.jpg',
      genre_ids: [27, 878, 53],
      id: 1284041,
      title: 'The Last House',
      original_language: 'en',
      original_title: 'The Last House',
      overview:
        'A family suddenly sealed inside their home must work together to survive against dwindling resources and the ominous threat keeping them trapped.',
      popularity: 218.8879,
      poster_path: '/6JU7E8Vv2M11egkctWVOScxWR75.jpg',
      release_date: '2026-08-06',
      softcore: false,
      video: false,
      vote_average: 6.911,
      vote_count: 898,
    },
    {
      adult: false,
      backdrop_path: '/rZfmzpixLKLR3Hg2u0WgC7XLFl8.jpg',
      genre_ids: [27, 53],
      id: 1339713,
      title: 'Obsession',
      original_language: 'en',
      original_title: 'Obsession',
      overview:
        'After breaking the mysterious "One Wish Willow" to win his crush\'s heart, a hopeless romantic finds himself getting exactly what he asked for but soon discovers that some desires come at a dark, sinister price.',
      popularity: 232.9651,
      poster_path: '/bRwnj8WEKBCvmfeUNOukJPwB43K.jpg',
      release_date: '2026-05-13',
      softcore: false,
      video: false,
      vote_average: 8.228,
      vote_count: 4852,
    },
    {
      adult: false,
      backdrop_path: '/b9q9VmbXDvJmTziRqkwdEmFdwhr.jpg',
      genre_ids: [878, 9648, 53],
      id: 1101383,
      title: 'The End of Oak Street',
      original_language: 'en',
      original_title: 'The End of Oak Street',
      overview:
        'After a mysterious cosmic event rips Oak Street from suburbia and transports their neighborhood to someplace unknown, the Platt family soon discovers that their very survival depends on them sticking together as they navigate their now unrecognizable surroundings.',
      popularity: 202.1509,
      poster_path: '/fYXqpgPmHMphSF2W30GbTeJVIa5.jpg',
      release_date: '2026-08-12',
      softcore: false,
      video: false,
      vote_average: 6.482,
      vote_count: 256,
    },
    {
      adult: false,
      backdrop_path: '/lh3BDkmWJh998n4fQcHYcVi7dpm.jpg',
      genre_ids: [12, 18, 28],
      id: 1284465,
      title: 'The Death of Robin Hood',
      original_language: 'en',
      original_title: 'The Death of Robin Hood',
      overview:
        'Grappling with his past after a life of crime and murder, Robin Hood finds himself gravely injured after a battle he thought would be his last. In the hands of a mysterious woman, he is offered a chance at salvation.',
      popularity: 204.5826,
      poster_path: '/92Tsfx7SFafOqWsotvrlJbHyehd.jpg',
      release_date: '2026-06-18',
      softcore: false,
      video: false,
      vote_average: 6.276,
      vote_count: 228,
    },
    {
      adult: false,
      backdrop_path: '/c6BPbkO5Npt1OdwttAxCFo06wtH.jpg',
      genre_ids: [10751, 14, 35, 12],
      id: 1108427,
      title: 'Moana',
      original_language: 'en',
      original_title: 'Moana',
      overview:
        "Teenage Moana answers the Ocean's call and, for the first time, voyages beyond the reef of her island of Motunui with infamous demigod Maui on an unforgettable journey to restore prosperity to her people.",
      popularity: 194.8449,
      poster_path: '/zKVgiv5qHCvCLT4A2ymJi5QeXDH.jpg',
      release_date: '2026-07-08',
      softcore: false,
      video: false,
      vote_average: 6.012,
      vote_count: 207,
    },
    {
      adult: false,
      backdrop_path: '/flxau5Iu7bChQHsESqvGZ3FQRaI.jpg',
      genre_ids: [878, 53],
      id: 1275779,
      title: 'Disclosure Day',
      original_language: 'en',
      original_title: 'Disclosure Day',
      overview:
        "A cybersecurity expert becomes a whistleblower after uncovering secrets about aliens, putting him on the run from a corporation. Meanwhile, a meteorologist experiencing strange phenomena joins forces with him to prove there's life beyond our understanding.",
      popularity: 167.6166,
      poster_path: '/AnJ8IQJI23hNpYXVNaythu061Ru.jpg',
      release_date: '2026-06-10',
      softcore: false,
      video: false,
      vote_average: 7.458,
      vote_count: 2905,
    },
    {
      adult: false,
      backdrop_path: '/o0jkkpcN81QqSl8DMLScBCXyUH9.jpg',
      genre_ids: [27],
      id: 1212763,
      title: 'Evil Dead Burn',
      original_language: 'en',
      original_title: 'Evil Dead Burn',
      overview:
        "After her husband's abrupt death, Alice seeks solace with his remaining family — descendants of a leading researcher on demonic possession. As her in-laws transform one by one into creatures that feed on fear, she comes to discover that the vows she took in life survive even in death.",
      popularity: 153.2715,
      poster_path: '/uRxrNXQWkHoENm3nwVOZDYSCx2F.jpg',
      release_date: '2026-07-07',
      softcore: false,
      video: false,
      vote_average: 7.9,
      vote_count: 1184,
    },
    {
      adult: false,
      backdrop_path: '/54KIfdTEzOliHDKx0OkzYGqAICx.jpg',
      genre_ids: [28, 12, 878],
      id: 1081003,
      title: 'Supergirl',
      original_language: 'en',
      original_title: 'Supergirl',
      overview:
        'When an unexpected and ruthless adversary strikes too close to home, Kara Zor-El, aka Supergirl, reluctantly joins forces with an unlikely companion on an epic, interstellar journey of vengeance and justice.',
      popularity: 131.9168,
      poster_path: '/1QCWdqzTfh2x9UylVpspIU6QTuM.jpg',
      release_date: '2026-06-24',
      softcore: false,
      video: false,
      vote_average: 6.745,
      vote_count: 1950,
    },
    {
      adult: false,
      backdrop_path: '/wcUohmHc9oDZXarXDp905TYVui4.jpg',
      genre_ids: [18, 10749],
      id: 82023,
      title: 'Hotel Desire',
      original_language: 'de',
      original_title: 'Hotel Desire',
      overview:
        'Antonia is a single mother who works as a hotel maid in Berlin. A normal hot summer day takes a dramatic turn when she crosses paths with a particular guest of the hotel, famous blind portrait painter Julius Pass.',
      popularity: 138.4892,
      poster_path: '/47XRWH95ATv4szxdWHl723guWXP.jpg',
      release_date: '2011-12-07',
      softcore: false,
      video: false,
      vote_average: 6.171,
      vote_count: 155,
    },
    {
      adult: false,
      backdrop_path: '/7t6f6VxA2ZXbbZSVctgt7bZG2DI.jpg',
      genre_ids: [27, 878, 53],
      id: 1307118,
      title: 'Soulm8te',
      original_language: 'en',
      original_title: 'Soulm8te',
      overview:
        'After a ruthless tech giant acquires a small robotics company, a grieving engineer is tasked with testing their new AI companion. But when he attempts to reprogram her to be a truly sentient soulmate, she develops needs of her own—unleashing a relentless spree of precision-engineered mayhem.',
      popularity: 120.8394,
      poster_path: '/bNErActDctl6cdUGw9pnjSCmyhQ.jpg',
      release_date: '2026-07-31',
      softcore: false,
      video: false,
      vote_average: 7.232,
      vote_count: 211,
    },
    {
      adult: false,
      backdrop_path: '/dqmMWNWfLnExDRpMtIMqI97GQFR.jpg',
      genre_ids: [27, 9648, 878],
      id: 1083381,
      title: 'Backrooms',
      original_language: 'en',
      original_title: 'Backrooms',
      overview:
        'A strange doorway appears in the basement of a furniture showroom.',
      popularity: 131.004,
      poster_path: '/rhGx6E3qRNMgj3i5su2oukNHwIQ.jpg',
      release_date: '2026-05-27',
      softcore: false,
      video: false,
      vote_average: 7.095,
      vote_count: 2856,
    },
    {
      adult: false,
      backdrop_path: '/s4v0UX1anfXm0UvloLsTTJ4v222.jpg',
      genre_ids: [878, 28, 12],
      id: 1003596,
      title: 'Avengers: Doomsday',
      original_language: 'en',
      original_title: 'Avengers: Doomsday',
      overview:
        "Beloved heroes from three distinct universes are set on a deadly collision course and face an existential threat unlike anything they've ever encountered.",
      popularity: 129.3192,
      poster_path: '/jzPwsojjFStf5lR5Nm07w2hH56G.jpg',
      release_date: '2026-12-16',
      softcore: false,
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: '/fn4n6uOYcB6Uh89nbNPoU2w80RV.jpg',
      genre_ids: [28, 12, 878],
      id: 315635,
      title: 'Spider-Man: Homecoming',
      original_language: 'en',
      original_title: 'Spider-Man: Homecoming',
      overview:
        'Following the events of Captain America: Civil War, Peter Parker, with the help of his mentor Tony Stark, tries to balance his life as an ordinary high school student in Queens, New York City, with fighting crime as his superhero alter ego Spider-Man as a new threat, the Vulture, emerges.',
      popularity: 118.0399,
      poster_path: '/c24sv2weTHPsmDa7jEMN0m2P3RT.jpg',
      release_date: '2017-07-05',
      softcore: false,
      video: false,
      vote_average: 7.333,
      vote_count: 23693,
    },
  ],
  total_pages: 58547,
  total_results: 1170921,
};
